apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lso-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: lso-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lso2/application-manifest
    repoURL: https://github.com/mfau007/customer2
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
