apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscovery
metadata:
#  name: discover-all-devices "Error using john's parameter " The LocalVolumeDiscovery "discover-all-devices" is invalid: metadata.name: Unsupported value: "discover-all-devices": supported values: "auto-discover-devices"
  name: auto-discover-devices
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
        - key: cluster.ocs.openshift.io/openshift-storage
          operator: Exists
