apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ocs-public
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  config: '{
  	"cniVersion": "0.3.1",
  	"type": "macvlan",
  	"master": "ens6",
  	"mode": "bridge",
  	"ipam": {
    	    "type": "whereabouts",
    	    "range": "10.0.192.0/19"
  	}
  }'
