apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ocs-storagecluster-cephblockpool-hdd
  namespace: openshift-storage
spec:
  compressionMode: none
  deviceClass: hdd
  erasureCoded:
    codingChunks: 0
    dataChunks: 0
  failureDomain: host
  mirroring: {}
  parameters:
    compression_mode: none
  quotas: {}
  replicated:
    size: 3
    targetSizeRatio: 0.49
