---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
# encryption:
# clusterWide: true ### this will use cryptsetup/LUKS for at-rest encryption
  flexibleScaling: true ### allow scaling by node/host instead of by "rack" or by "zone"
  monDataDirHostPath: /var/lib/rook
    #  network:
    #  ipFamily: IPv4
    #    provider: multus
    #    selectors:
    #      public: openshift-storage/ocs-public
    #      cluster: openshift-storage/ocs-cluster
  storageDeviceSets:
    - config: {}
      count: 3
      dataPVCTemplate:
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '1'
          storageClassName: local-nvme
          volumeMode: Block
        status: {}
      deviceType: nvme
      name: nvme
      placement: {}
      preparePlacement: {}
      replica: 1
      resources: {}
    - config: {}
      count: 3
      dataPVCTemplate:
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '1'
          storageClassName: local-hdd
          volumeMode: Block
        status: {}
      deviceType: hdd
      name: hdd
      placement: {}
      preparePlacement: {}
      replica: 1
      resources: {}
  managedResources:
    cephBlockPools:
      reconcileStrategy: ignore ###don't create the default CephBlockPool nor the RBD S
# cephFilesystems:
# reconcileStrategy: ignore ###don't create the default CephFilesystem nor the Cep
  multiCloudGateway:
    dbStorageClassName: ocs-storagecluster-ceph-rbd-nvme
